'use client'

import { createContext, useContext, useEffect, useRef, useState } from 'react'

type Theme = 'light' | 'dark'
type Language = 'bn' | 'en'

interface AppContextType {
  theme: Theme
  toggleTheme: () => void
  language: Language
  setLanguage: (l: Language) => void
  sidebarCollapsed: boolean
  toggleSidebar: () => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  bn: {
    'dashboard': 'ড্যাশবোর্ড',
    'orders': 'অর্ডার',
    'orders_list': 'অর্ডার তালিকা',
    'fake_customers': 'ফেক গ্রাহক',
    'fake_customers_subtitle': 'প্রতারণামূলক বা সন্দেহজনক গ্রাহকদের তালিকা',
    'marked_by_admin': 'অ্যাডমিন দ্বারা চিহ্নিত',
    'refresh': 'রিফ্রেশ',
    'reason': 'কারণ',
    'detection': 'শনাক্তকরণ',
    'products': 'পণ্য',
    'products_list': 'পণ্যের তালিকা',
    'customers': 'গ্রাহক',
    'analytics': 'বিশ্লেষণ',
    'marketing': 'মার্কেটিং',
    'courier': 'কুরিয়ার',
    'payments': 'পেমেন্ট গেটওয়ে',
    'coupons': 'কুপন',
    'abandoned_cart': 'পরিত্যক্ত কার্ট',
    'settings': 'সেটিংস',
    'tracking': 'ট্র্যাকিং স্ক্রিপ্ট',
    'users': 'ইউজার ম্যানেজমেন্ট',
    'pages': 'পেজসমূহ',
    'roles': 'ভূমিকা ও অনুমতি',
    'activity_log': 'কার্যকলাপ লগ',
    'total_revenue': 'মোট রাজস্ব',
    'total_orders': 'মোট অর্ডার',
    'total_customers': 'মোট গ্রাহক',
    'avg_order_value': 'গড় অর্ডার মূল্য',
    'low_stock_alerts': '⚠ কম স্টক সতর্কতা',
    'abandoned_carts': '🛒 পরিত্যক্ত কার্ট',
    'recent_orders': 'সাম্প্রতিক অর্ডার',
    'top_products': 'শীর্ষ পণ্য',
    'sales_overview': 'বিক্রয় সংক্ষিপ্তসার',
    'vs_last_month': 'গত মাসের তুলনায়',
    'search': 'খুঁজুন...',
    'new_order': 'নতুন অর্ডার',
    'new_product': 'নতুন পণ্য',
    'logout': 'লগ আউট',
    'profile': 'প্রোফাইল',
    'name': 'নাম',
    'status': 'অবস্থা',
    'price': 'মূল্য',
    'stock': 'স্টক',
    'category': 'ক্যাটাগরি',
    'action': 'কার্যক্রম',
    'pending': 'অপেক্ষমাণ',
    'confirmed': 'নিশ্চিত',
    'dispatched': 'প্রেরিত',
    'delivered': 'বিতরণ',
    'cancelled': 'বাতিল',
    'returned': 'ফেরত',
    'processing': 'প্রক্রিয়াকরণ',
    'shipped': 'প্রেরিত',
    'on_hold': 'বিরতিতে',
    'on_the_way': 'পথে আছে',
    'in_courier': 'কুরিয়ারে',
    'export': 'এক্সপোর্ট',
    'in_stock': 'স্টকে আছে',
    'low_stock': 'কম স্টক',
    'out_of_stock': 'স্টকে নেই',
    'style_bd': 'স্টাইল বিডি',
    'command_center': 'কমান্ড সেন্টার',
    'ai_recommendations': 'AI সুপারিশ',
    'setup': 'সেটআপ',
    'media': 'মিডিয়া',
    'customer_info': 'গ্রাহক তথ্য',
    'order_notes': 'অর্ডার নোট',
    'order_items': 'পণ্যের তালিকা',
    'subtotal': 'সাবটোটাল',
    'delivery': 'ডেলিভারি',
    'total': 'মোট',
    'payment_method': 'পেমেন্ট মাধ্যম',
    'cancel_order': 'বাতিল করুন',
    'invoice': 'ইনভয়েস',
    'all': 'সব',
    'search_orders': 'অর্ডার ID বা গ্রাহক খুঁজুন...',
    'no_orders_found': 'কোনো অর্ডার পাওয়া যায়নি',
    'order': 'অর্ডার',
    'customer': 'গ্রাহক',
    'product': 'পণ্য',
    'date': 'তারিখ',
    'revenue': 'রাজস্ব',
    'confirm_order': 'অর্ডার নিশ্চিত করুন',
    'send_order': 'প্রেরণ করুন',
    'delivered_order': 'বিতরণ হয়েছে',
    'support': 'সাপোর্ট',
    'dashboard_subtitle': 'আপনার ব্যবসার সম্পূর্ণ চিত্র একনজরে',
    'items_below_stock': 'পণ্য ১০ এর নিচে স্টক',
    'potential_recovery': 'সম্ভাব্য রিকভারি',
    'view_all': 'সব দেখুন',
    'order_id': 'অর্ডার আইডি',
    'traffic_source': 'ট্রাফিক সোর্স',
    'threshold': 'থ্রেসহোল্ড',
    'remaining': 'বাকি',
    'sufficient_stock': 'সব পণ্যের স্টক পর্যাপ্ত আছে',
    'smart_forecast': 'স্মার্ট পূর্বাভাস দেখুন',
    'ai_recommendation': 'AI সুপারিশ',
    'kurti_demand_alert': 'আগামী ৭ দিনে Kurti এর চাহিদা ৩২% বাড়তে পারে। স্টক রিঅর্ডার করার পরামর্শ দেওয়া হচ্ছে।',
    'carts': 'টি কার্ট',
    'new_customers': 'নতুন গ্রাহক',
    'deep_driver': 'ডিপ ড্রাইভার (বিশ্লেষণ)',
    'recover': 'রিকভার',
    'server_status': 'সার্ভার স্ট্যাটাস',
    'active': 'সক্রিয়',
    'product_name': 'পণ্যের নাম',
    'product_name_bn': 'পণ্যের নাম (বাংলা)',
    'selling_price': 'বিক্রয় মূল্য',
    'regular_price': 'নিয়মিত মূল্য',
    'cost_price': 'ক্রয় মূল্য',
    'delivery_inside': 'ঢাকার ভেতরে ডেলিভারি',
    'delivery_outside': 'ঢাকার বাইরে ডেলিভারি',
    'description_bn': 'বিবরণ (বাংলা)',
    'product_images': 'পণ্যের ছবি',
    'upload_hint': 'JPG, PNG, WEBP · সব সাইজ সমর্থিত',
    'uploading': 'আপলোড হচ্ছে...',
    'edit_product': 'পণ্য এডিট করুন',
    'add_new_product': 'নতুন পণ্য যোগ করুন',
    'new_arrivals': 'নতুন কালেকশন ম্যানেজার',
    'delete_confirm': 'এই পণ্যটি কি ডিলিট করতে চান?',
    'set_main': 'মূল ছবি করুন',
    'main': 'মূল',
    'inventory_breakdown': 'ইনভেন্টরি বিবরণ',
    'pcs': 'টি',
    'sku': 'SKU',
    'subtype': 'সাবটাইপ',
    'fabric': 'ফেব্রিক',
    'color': 'রঙ',
    'low_stock_threshold': 'কম স্টকের থ্রেসহোল্ড',
    'margin': 'মার্জিন',
    'media_manager': 'মিডিয়া ম্যানেজার',
    'upload_image': 'ছবি আপলোড',
    'total_images': 'মোট ছবি',
    'product_folders': 'পণ্য ফোল্ডার',
    'total_size': 'মোট সাইজ',
    'drag_drop_hint': 'ছবি টেনে এখানে ফেলুন অথবা ক্লিক করুন',
    'max_size_hint': 'PNG, JPG, WEBP · সর্বোচ্চ 20MB',
    'search_media': 'পণ্য কোড বা ফাইলের নাম খুঁজুন...',
    'grid_size': 'গ্রিড সাইজ',
    'images_selected': 'টি ছবি নির্বাচিত',
    'select_all': 'সব নির্বাচন',
    'delete': 'মুছুন',
    'clear_all': 'সব মুছুন',
    'browse_media': 'মিডিয়া ব্রাউজ',
    'upload': 'আপলোড',
    'total_spent': 'মোট ব্যয়',
    'avg_order': 'গড় অর্ডার',
    'contact_info': 'যোগাযোগ তথ্য',
    'note': 'নোট',
    'order_history': 'অর্ডার ইতিহাস',
    'message': 'মেসেজ করুন',
    'edit': 'সম্পাদনা',
    'save_customer': 'সেভ করুন',
    'customer_name': 'নাম',
    'phone_number': 'ফোন নম্বর',
    'email': 'ইমেইল',
    'address': 'ঠিকানা',
    'segment': 'সেগমেন্ট',
    'joined': 'যোগদান',
    'last_order': 'শেষ অর্ডার',
    'vip': 'VIP',
    'regular': 'নিয়মিত',
    'new': 'নতুন',
    'at_risk': 'ঝুঁকিতে',
    'inactive': 'নিষ্ক্রিয়',
    'all_customers': 'সব গ্রাহক',
    'search_customers': 'নাম, ফোন বা ইমেইল দিয়ে খুঁজুন...',
    'no_customers_found': 'কোনো গ্রাহক পাওয়া যায়নি',
    'ltv': 'LTV',
    'abandoned_cart_subtitle': 'পরিত্যক্ত কার্ট ট্র্যাক করুন এবং রিকভার করুন',
    'recovered_carts': 'রিকভার হয়েছে',
    'recovered_value': 'রিকভার মূল্য',
    'recovery_rate': 'রিকভারি হার',
    'active_abandoned_carts': 'সক্রিয় পরিত্যক্ত কার্ট',
    'all_recovered_hint': 'সব কার্ট রিকভার হয়েছে! 🎉',
    'hours_ago': 'ঘণ্টা আগে',
    'contacted': 'যোগাযোগ করা হয়েছে',
    'send_recovery_email': 'রিকভারি ইমেইল পাঠান',
    'send_sms': 'SMS পাঠান',
    'mark_recovered': 'রিকভার হিসেবে চিহ্নিত করুন',
    'email_sent': 'ইমেইল পাঠানো হয়েছে!',
    'payment_gateways': 'পেমেন্ট গেটওয়ে সংযোগ ও পরিচালনা',
    'active_gateways': 'সক্রিয় গেটওয়ে',
    'total_gateways': 'মোট গেটওয়ে',
    'pending_config': 'কনফিগার বাকি',
    'not_configured': 'কনফিগার করা হয়নি',
    'configure': 'কনফিগার করুন',
    'test_mode': 'টেস্ট মোড',
    'live_mode': 'লাইভ মোড',
    'save_settings': 'সেটিংস সেভ করুন',
    'saved_successfully': 'সেভ হয়েছে!',
    'charge': 'চার্জ',
    'online_gateway': 'অনলাইন গেটওয়ে',
    'mobile_banking': 'মোবাইল ব্যাংকিং',
    'security_hint': 'সমস্ত পেমেন্ট ট্রানজেকশন SSL এনক্রিপ্টেড। আপনার API Key গুলো কখনও সার্ভার লগে সংরক্ষিত হবে না।',
    'courier_management': 'কুরিয়ার পার্টনার সংযোগ এবং API ম্যানেজমেন্ট',
    'connected': 'সংযুক্ত',
    'temporarily_closed': 'সাময়িকভাবে বন্ধ',
    'time': 'সময়',
    'days': 'দিন',
    'api_security_hint': 'API কী গুলো সুরক্ষিতভাবে সংরক্ষিত থাকে। কাউকে শেয়ার করবেন না।',
    'delivery_charge': 'ডেলিভারি চার্জ',
    'cod_charge': 'COD চার্জ',
    'open_portal': 'পোর্টাল খুলুন',
    'how_it_works': 'কীভাবে কাজ করে',
    'courier_connected_hint': 'টি কুরিয়ার সংযুক্ত আছে। অর্ডার তৈরির সময় সয়ংক্রিয়ভাবে শিপমেন্ট তৈরি হবে।',
    'no_courier_hint': 'এখনো কোনো কুরিয়ার সংযুক্ত নেই। নিচে API Key দিয়ে সংযোগ করুন।',
    'step_1_title': 'API Key দিন',
    'step_1_desc': 'কুরিয়ার পার্টনারের পোর্টাল থেকে API Key নিন এবং এখানে পেস্ট করুন।',
    'step_2_title': 'অর্ডার তৈরি করুন',
    'step_2_desc': 'অর্ডার কনফার্ম করলেই সয়ংক্রিয়ভাবে কুরিয়ারে পাঠানো হবে।',
    'step_3_title': 'ট্র্যাক করুন',
    'step_3_desc': 'রিয়েল-টাইম ট্র্যাকিং নম্বর পাবেন এবং গ্রাহককে SMS যাবে।',
    'taxonomy_setup': 'ট্যাক্সোনমি সেটআপ',
    'product_setup_mgmt': 'পণ্য সেটআপ ম্যানেজমেন্ট',
    'product_setup_subtitle': 'আপনার দোকানের ক্যাটাগরি, সাইজ, রঙ এবং ফেব্রিক আগে থেকে কনফিগার করুন।',
    'categories': 'ক্যাটাগরি',
    'fashion_specs': 'ফ্যাশন স্পেকস',
    'brands': 'ব্র্যান্ড',
    'dynamic_attributes': 'ডায়নামিক অ্যাট্রিবিউট',
    'category_hierarchy': 'ক্যাটাগরি হায়ারার্কি',
    'manage_nested_categories': 'নেস্টেড ক্যাটাগরি পরিচালনা করুন',
    'root_category': 'মূল ক্যাটাগরি',
    'pro_tip': 'প্রো টিপ',
    'quick_actions': 'কুইক অ্যাকশন',
    'manage_fabrics': 'ফেব্রিক/মেটেরিয়াল পরিচালনা করুন',
    'bulk_import': 'বাল্ক ইম্পোর্ট',
    'sizes': 'সাইজ',
    'colors': 'রঙ',
    'fabrics': 'ফেব্রিক',
    'multi_color': 'মাল্টি-কালার',
    'solid_color': 'সলিড কালার',
    'color_suggestions': 'রঙের পরামর্শ',
    'registered_brands': 'নিবন্ধিত ব্র্যান্ড',
    'category_attributes': 'ক্যাটাগরি অ্যাট্রিবিউট',
    'add_new': 'নতুন যোগ করুন',
    'category_name_en': 'ক্যাটাগরি নাম (ইংরেজি)',
    'category_name_bn': 'ক্যাটাগরি নাম (বাংলা)',
    'size_format': 'সাইজ ফরম্যাট',
    'standard_apparel': 'স্ট্যান্ডার্ড পোশাক সাইজ (S, M, XL)',
    'numeric_measurement': 'সংখ্যার মাপ (42, 24 ইঞ্চি)',
    'measurement_value': 'মাপের মান',
    'size_name': 'সাইজের নাম',
    'measurement_unit': 'মাপের একক',
    'size_code': 'সাইজ কোড',
    'pattern_description': 'প্যাটার্ন বিবরণ',
    'settings_subtitle': 'স্টোর কনফিগারেশন, অ্যাকাউন্ট এবং ইন্টিগ্রেশন ম্যানেজমেন্ট',
    'store_info': 'স্টোর তথ্য',
    'account': 'অ্যাকাউন্ট',
    'notifications': 'নোটিফিকেশন',
    'security': 'নিরাপত্তা',
    'integrations': 'ইন্টিগ্রেশন',
    'save_changes': 'পরিবর্তন সেভ করুন',
    'brand_info': 'ব্র্যান্ড তথ্য',
    'tagline': 'ট্যাগলাইন',
    'regional_settings': 'আঞ্চলিক সেটিংস',
    'currency': 'মুদ্রা',
    'timezone': 'টাইমজোন',
    'free_shipping_threshold': 'ফ্রি শিপিং (৳ এর উপরে)',
    'theme_and_language': 'থিম ও ভাষা',
    'light': 'লাইট',
    'dark': 'ডার্ক',
    'profile_info': 'প্রোফাইল তথ্য',
    'change_photo': 'ছবি পরিবর্তন করুন',
    'role': 'ভূমিকা (Role)',
    'notification_preferences': 'নোটিফিকেশন প্রেফারেন্স',
    'change_password': 'পাসওয়ার্ড পরিবর্তন',
    'current_password': 'বর্তমান পাসওয়ার্ড',
    'new_password': 'নতুন পাসওয়ার্ড',
    'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
    'session_management': 'সেশন ম্যানেজমেন্ট',
    'current_session_secure': 'বর্তমান সেশন নিরাপদ',
    'logout_all': 'সব ডিভাইস থেকে লগআউট করুন',
    'marketing_tracking': 'মার্কেটিং ট্র্যাকিং',
    'payment_gateway': 'পেমেন্ট গেটওয়ে',
    'social_media': 'সোশ্যাল মিডিয়া',
    'analytics_subtitle': 'বিক্রয়, ট্রাফিক এবং পারফরম্যান্স বিশ্লেষণ',
    'today': 'আজ',
    'last_7_days': 'গত ৭ দিন',
    'this_month': 'এই মাস',
    'last_month': 'গত মাস',
    'this_year': 'এই বছর',
    'custom': 'কাস্টম',
    'total_sales': 'মোট বিক্রয়',
    'conversion_rate': 'রূপান্তর হার',
    'ad_spend': 'অ্যাড ব্যয়',
    'net_profit': 'নেট মুনাফা',
    'roi': 'ROI',
    'revenue_vs_ad_spend': 'রেভিনিউ বনাম অ্যাড ব্যয়',
    'order_funnel': 'অর্ডার ফানেল (কনভার্সন)',
    'sold': 'বিক্রীত',
    'trend': 'ট্রেন্ড',
    'campaign_mgmt': 'ক্যাম্পেইন ম্যানেজমেন্ট এবং মার্কেটিং পারফরম্যান্স',
    'total_ad_spend': 'মোট বিজ্ঞাপন ব্যয়',
    'total_reach': 'মোট নাগাল',
    'total_clicks': 'মোট ক্লিক',
    'avg_roas': 'গড় ROAS',
    'active_campaigns': 'সক্রিয় ক্যাম্পেইন',
    'new_campaign': 'নতুন ক্যাম্পেইন',
    'running': 'চলছে',
    'paused': 'বিরতি',
    'spend': 'ব্যয়',
    'reach': 'নাগাল',
    'clicks': 'ক্লিক',
    'roas': 'ROAS',
    'ad_creator': 'বিজ্ঞাপন তৈরি করুন (Ad Creator)',
    'ad_headline': 'বিজ্ঞাপন শিরোনাম',
    'ad_body': 'বিজ্ঞাপনের বিবরণ',
    'budget_per_day': 'বাজেট (BDT/দিন)',
    'duration_days': 'মেয়াদ (দিন)',
    'total_budget': 'মোট বাজেট',
    'start_campaign': 'ক্যাম্পেইন শুরু করুন',
    'ad_preview': 'বিজ্ঞাপন প্রিভিউ',
    'sponsored': 'Sponsored',
    'ad_placeholder_title': 'আপনার বিজ্ঞাপনের শিরোনাম',
    'ad_placeholder_body': 'বিজ্ঞাপনের বিবরণ এখানে দেখাবে...',
    'coupons_subtitle': 'ডিসকাউন্ট কুপন তৈরি ও পরিচালনা করুন',
    'new_coupon': 'নতুন কুপন',
    'active_coupons': 'সক্রিয় কুপন',
    'total_used': 'মোট ব্যবহার',
    'expired': 'মেয়াদ শেষ',
    'search_coupons': 'কুপন কোড খুঁজুন...',
    'usage': 'ব্যবহার',
    'min_order': 'সর্বনিম্ন অর্ডার',
    'expires': 'মেয়াদ',
    'percentage_off': '% শতাংশ ছাড়',
    'flat_off': '৳ ফ্ল্যাট ছাড়',
    'edit_coupon': 'কুপন সম্পাদনা',
    'create_new_coupon': 'নতুন কুপন তৈরি করুন',
    'coupon_code': 'কুপন কোড',
    'coupon_type': 'কুপনের ধরন',
    'usage_limit': 'ব্যবহার সীমা',
    'expiry_date': 'মেয়াদ শেষ তারিখ',
    'active_caps': 'সক্রিয়',
    'inactive_caps': 'নিষ্ক্রিয়',
    'deactivate': 'নিষ্ক্রিয় করুন',
    'activate': 'সক্রিয় করুন',
    'admin_user': 'অ্যাডমিন ইউজার',
    'super_admin': 'সুপার অ্যাডমিন',
    'product_count': 'পণ্য',
    'cart_count': 'কার্ট',
    'no_items_hint': 'এখনও কোনো আইটেম যোগ করা হয়নি',
    'size': 'সাইজ',
    'brand': 'ব্র্যান্ড',
    'attribute': 'বৈশিষ্ট্য',
    'new_order_notice': 'অ্যাডমিন প্যানেল থেকে ম্যানুয়াল অর্ডার তৈরি করা বর্তমানে বন্ধ আছে। অনুগ্রহ করে স্টোরফ্রন্ট থেকে অর্ডার করুন।',
  },
  en: {
    'dashboard': 'Dashboard',
    'orders': 'Orders',
    'orders_list': 'Orders List',
    'fake_customers': 'Fake Customers',
    'fake_customers_subtitle': 'List of fraudulent or suspicious customers',
    'marked_by_admin': 'Marked by Admin',
    'refresh': 'Refresh',
    'reason': 'Reason',
    'detection': 'Detection',
    'products': 'Products',
    'products_list': 'Products List',
    'customers': 'Customers',
    'analytics': 'Analytics',
    'marketing': 'Marketing',
    'courier': 'Courier',
    'payments': 'Payment Gateways',
    'coupons': 'Coupons',
    'abandoned_cart': 'Abandoned Carts',
    'settings': 'Settings',
    'tracking': 'Tracking Scripts',
    'users': 'User Management',
    'pages': 'Pages',
    'roles': 'Roles & Permissions',
    'activity_log': 'Activity Log',
    'total_revenue': 'Total Revenue',
    'total_orders': 'Total Orders',
    'total_customers': 'Total Customers',
    'avg_order_value': 'Avg. Order Value',
    'low_stock_alerts': '⚠ Low Stock Alerts',
    'abandoned_carts': '🛒 Abandoned Carts',
    'recent_orders': 'Recent Orders',
    'top_products': 'Top Products',
    'sales_overview': 'Sales Overview',
    'vs_last_month': 'vs last month',
    'search': 'Search...',
    'new_order': 'New Order',
    'new_product': 'New Product',
    'logout': 'Logout',
    'profile': 'Profile',
    'name': 'Name',
    'status': 'Status',
    'price': 'Price',
    'stock': 'Stock',
    'category': 'Category',
    'action': 'Action',
    'pending': 'Pending',
    'confirmed': 'Confirmed',
    'dispatched': 'Dispatched',
    'delivered': 'Delivered',
    'cancelled': 'Cancelled',
    'returned': 'Returned',
    'processing': 'Processing',
    'shipped': 'Shipped',
    'on_hold': 'On Hold',
    'on_the_way': 'On The Way',
    'in_courier': 'In Courier',
    'export': 'Export',
    'in_stock': 'In Stock',
    'low_stock': 'Low Stock',
    'out_of_stock': 'Out of Stock',
    'style_bd': 'style-bd',
    'command_center': 'Command Center',
    'ai_recommendations': 'AI Recommendations',
    'setup': 'Setup',
    'media': 'Media',
    'customer_info': 'Customer Info',
    'order_notes': 'Order Notes',
    'order_items': 'Order Items',
    'subtotal': 'Subtotal',
    'delivery': 'Delivery',
    'total': 'Total',
    'payment_method': 'Payment Method',
    'cancel_order': 'Cancel Order',
    'invoice': 'Invoice',
    'all': 'All',
    'search_orders': 'Search Order ID or customer...',
    'no_orders_found': 'No orders found',
    'order': 'Order',
    'customer': 'Customer',
    'product': 'Product',
    'date': 'Date',
    'revenue': 'Revenue',
    'confirm_order': 'Confirm Order',
    'send_order': 'Send Order',
    'delivered_order': 'Delivered',
    'support': 'Support',
    'dashboard_subtitle': 'A complete overview of your business at a glance',
    'items_below_stock': 'items below 10 stock',
    'potential_recovery': 'potential recovery',
    'view_all': 'View All',
    'order_id': 'Order ID',
    'traffic_source': 'Traffic Source',
    'threshold': 'Threshold',
    'remaining': 'remaining',
    'sufficient_stock': 'All products have sufficient stock',
    'smart_forecast': 'Smart Forecast',
    'ai_recommendation': 'AI Recommendation',
    'kurti_demand_alert': 'Kurti demand may increase by 32% in the next 7 days. Reordering stock is recommended.',
    'carts': 'carts',
    'new_customers': 'New Customers',
    'deep_driver': 'Deep Driver (Analytics)',
    'recover': 'Recover',
    'server_status': 'Server Status',
    'active': 'Active',
    'product_name': 'Product Name',
    'product_name_bn': 'Product Name (Bangla)',
    'selling_price': 'Selling Price',
    'regular_price': 'Regular Price',
    'cost_price': 'Cost Price',
    'delivery_inside': 'Delivery (Inside Dhaka)',
    'delivery_outside': 'Delivery (Outside Dhaka)',
    'description_bn': 'Description (Bangla)',
    'product_images': 'Product Images',
    'upload_hint': 'JPG, PNG, WEBP · All sizes supported',
    'uploading': 'Uploading...',
    'edit_product': 'Edit Product',
    'add_new_product': 'Add New Product',
    'new_arrivals': 'New Arrivals Manager',
    'delete_confirm': 'Delete this product?',
    'set_main': 'Set Main',
    'main': 'MAIN',
    'inventory_breakdown': 'Inventory Breakdown',
    'pcs': 'pcs',
    'sku': 'SKU',
    'subtype': 'Subtype',
    'fabric': 'Fabric',
    'color': 'Color',
    'low_stock_threshold': 'Low Stock Threshold',
    'margin': 'Margin',
    'media_manager': 'Media Manager',
    'upload_image': 'Upload Image',
    'total_images': 'Total Images',
    'product_folders': 'Product Folders',
    'total_size': 'Total Size',
    'drag_drop_hint': 'Drag and drop images here or click',
    'max_size_hint': 'PNG, JPG, WEBP · Max 20MB',
    'search_media': 'Search product code or filename...',
    'grid_size': 'Grid Size',
    'images_selected': 'images selected',
    'select_all': 'Select All',
    'delete': 'Delete',
    'clear_all': 'Clear All',
    'social_media': 'Social Media',
    'analytics_subtitle': 'Sales, Traffic & Performance Analysis',
    'today': 'Today',
    'last_7_days': 'Last 7 Days',
    'this_month': 'This Month',
    'last_month': 'Last Month',
    'this_year': 'This Year',
    'custom': 'Custom',
    'total_sales': 'Total Sales',
    'conversion_rate': 'Conversion Rate',
    'ad_spend': 'Ad Spend',
    'net_profit': 'Net Profit',
    'roi': 'ROI',
    'revenue_vs_ad_spend': 'Revenue vs Ad Spend',
    'order_funnel': 'Order Funnel (Conversion)',
    'sold': 'Sold',
    'trend': 'Trend',
    'campaign_mgmt': 'Campaign Management & Marketing Performance',
    'total_ad_spend': 'Total Ad Spend',
    'total_reach': 'Total Reach',
    'total_clicks': 'Total Clicks',
    'avg_roas': 'Avg ROAS',
    'active_campaigns': 'Active Campaigns',
    'new_campaign': 'New Campaign',
    'running': 'Running',
    'paused': 'Paused',
    'spend': 'Spend',
    'reach': 'Reach',
    'clicks': 'Clicks',
    'roas': 'ROAS',
    'ad_creator': 'Ad Creator',
    'ad_headline': 'Ad Headline',
    'ad_body': 'Ad Body',
    'budget_per_day': 'Budget (BDT/Day)',
    'duration_days': 'Duration (Days)',
    'total_budget': 'Total Budget',
    'start_campaign': 'Start Campaign',
    'ad_preview': 'Ad Preview',
    'sponsored': 'Sponsored',
    'ad_placeholder_title': 'Your Ad Headline',
    'ad_placeholder_body': 'Ad body description will appear here...',
    'coupons_subtitle': 'Create & Manage Discount Coupons',
    'new_coupon': 'New Coupon',
    'active_coupons': 'Active Coupons',
    'total_used': 'Total Used',
    'expired': 'Expired',
    'search_coupons': 'Search Coupons...',
    'usage': 'Usage',
    'min_order': 'Min Order',
    'expires': 'Expires',
    'percentage_off': '% Percentage Off',
    'flat_off': '৳ Flat Off',
    'edit_coupon': 'Edit Coupon',
    'create_new_coupon': 'Create New Coupon',
    'coupon_code': 'Coupon Code',
    'coupon_type': 'Coupon Type',
    'usage_limit': 'Usage Limit',
    'expiry_date': 'Expiry Date',
    'active_caps': 'Active',
    'inactive_caps': 'Inactive',
    'deactivate': 'Deactivate',
    'activate': 'Activate',
    'admin_user': 'Admin User',
    'super_admin': 'Super Admin',
    'product_count': 'products',
    'cart_count': 'carts',
    'no_items_hint': 'No items added yet',
    'size': 'Size',
    'brand': 'Brand',
    'attribute': 'Attribute',
    'new_order_notice': 'Manual order creation via admin panel is currently disabled. Please place orders via the storefront.',
    'upload': 'Upload',
    'email_sent': 'Email Sent!',
    'payment_gateways': 'Payment Gateway Connection & Management',
    'active_gateways': 'Active Gateways',
    'total_gateways': 'Total Gateways',
    'pending_config': 'Pending Config',
    'not_configured': 'Not Configured',
    'configure': 'Configure',
    'test_mode': 'Test Mode',
    'live_mode': 'Live Mode',
    'save_settings': 'Save Settings',
    'saved_successfully': 'Saved Successfully!',
    'inactive': 'Inactive',
    'charge': 'Charge',
    'online_gateway': 'Online Gateway',
    'mobile_banking': 'Mobile Banking',
    'security_hint': 'All payment transactions are SSL encrypted. Your API Keys will never be stored in server logs.',
    'courier_management': 'Courier Partner Connection & API Management',
    'connected': 'Connected',
    'temporarily_closed': 'Temporarily Closed',
    'time': 'Time',
    'days': 'days',
    'api_security_hint': 'API keys are stored securely. Do not share with anyone.',
    'delivery_charge': 'Delivery Charge',
    'cod_charge': 'COD Charge',
    'open_portal': 'Open Portal',
    'how_it_works': 'How it Works',
    'courier_connected_hint': 'couriers are connected. Shipments will be created automatically when orders are confirmed.',
    'no_courier_hint': 'No couriers connected yet. Use API Keys below to connect.',
    'step_1_title': 'Provide API Key',
    'step_1_desc': 'Get API keys from your courier partner portal and paste them here.',
    'step_2_title': 'Create Orders',
    'step_2_desc': 'Shipments will be automatically created once orders are confirmed.',
    'step_3_title': 'Track Orders',
    'step_3_desc': 'Receive real-time tracking numbers and SMS updates for customers.',
    'taxonomy_setup': 'Taxonomy Setup',
    'product_setup_mgmt': 'Product Setup Management',
    'product_setup_subtitle': 'Pre-configure your shop\'s categories, sizes, colors, and fabrics for a streamlined workflow.',
    'categories': 'Categories',
    'fashion_specs': 'Fashion Specs',
    'brands': 'Brands',
    'dynamic_attributes': 'Dynamic Attributes',
    'category_hierarchy': 'Category Hierarchy',
    'manage_nested_categories': 'Manage nested categories (Sub & Child)',
    'root_category': 'Root Category',
    'pro_tip': 'Pro Tip',
    'quick_actions': 'Quick Actions',
    'manage_fabrics': 'Manage Fabrics/Materials',
    'bulk_import': 'Bulk Import',
    'sizes': 'Sizes',
    'colors': 'Colors',
    'fabrics': 'Fabrics',
    'multi_color': 'Multi-Color',
    'solid_color': 'Solid Color',
    'color_suggestions': 'Color Suggestions',
    'registered_brands': 'Registered Brands',
    'category_attributes': 'Category Attributes',
    'add_new': 'Add New',
    'category_name_en': 'Category Name (EN)',
    'category_name_bn': 'Category Name (BN)',
    'size_format': 'Size Format',
    'standard_apparel': 'Standard Apparel Size (S, M, XL)',
    'numeric_measurement': 'Numeric Measurement (42, 24 Inch)',
    'measurement_value': 'Measurement Value',
    'size_name': 'Size Name',
    'measurement_unit': 'Measurement Unit',
    'size_code': 'Size Code',
    'pattern_description': 'Pattern Description',
    'total_spent': 'Total Spent',
    'avg_order': 'Avg Order',
    'contact_info': 'Contact Info',
    'note': 'Note',
    'order_history': 'Order History',
    'message': 'Message',
    'edit': 'Edit',
    'save_customer': 'Save Customer',
    'customer_name': 'Name',
    'phone_number': 'Phone Number',
    'email': 'Email',
    'address': 'Address',
    'segment': 'Segment',
    'joined': 'Joined',
    'last_order': 'Last Order',
    'vip': 'VIP',
    'regular': 'Regular',
    'new': 'New',
    'at_risk': 'At Risk',
    'all_customers': 'All Customers',
    'search_customers': 'Search name, phone or email...',
    'no_customers_found': 'No customers found',
    'ltv': 'LTV',
  },
}

const AppContext = createContext<AppContextType | undefined>(undefined)

export function AppProvider({ children }: { children: React.ReactNode }) {
  // Always start with server-safe defaults — prevents hydration mismatch
  const [theme, setTheme] = useState<Theme>('dark')
  const [language, setLanguage] = useState<Language>('en')
  const [sidebarCollapsed, setSidebarCollapsed] = useState<boolean>(false)
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    // Read all persisted values at once after hydration
    const savedTheme = (localStorage.getItem('theme') as Theme) || 'dark'
    const savedLang = (localStorage.getItem('language') as Language) || 'en'
    const savedCollapsed = localStorage.getItem('sidebarCollapsed') === 'true'

    // Apply theme class
    document.documentElement.classList.toggle('dark', savedTheme === 'dark')

    // Apply sidebar CSS variable + data attribute (already set by head script,
    // but we re-confirm here to keep React state in sync)
    document.documentElement.style.setProperty('--sidebar-width', savedCollapsed ? '64px' : '256px')
    document.documentElement.setAttribute('data-sidebar-collapsed', String(savedCollapsed))

    setTheme(savedTheme)
    setLanguage(savedLang)
    setSidebarCollapsed(savedCollapsed)
    setMounted(true)
  }, [])

  const toggleTheme = () => {
    const next = theme === 'light' ? 'dark' : 'light'
    setTheme(next)
    localStorage.setItem('theme', next)
    document.documentElement.classList.toggle('dark', next === 'dark')
  }

  const handleSetLanguage = (l: Language) => {
    setLanguage(l)
    localStorage.setItem('language', l)
  }

  const toggleSidebar = () => setSidebarCollapsed(p => {
    const next = !p
    localStorage.setItem('sidebarCollapsed', String(next))
    document.documentElement.style.setProperty('--sidebar-width', next ? '64px' : '256px')
    document.documentElement.setAttribute('data-sidebar-collapsed', String(next))
    return next
  })

  const t = (key: string) => translations[language][key] ?? key

  return (
    <AppContext.Provider value={{ theme, toggleTheme, language, setLanguage: handleSetLanguage, sidebarCollapsed, toggleSidebar, t }}>
      {/*
        The layout chrome (Sidebar + TopBar) is purely CSS-variable driven,
        so it looks correct even before mounted=true (no visibility flicker).
        We only need mounted for components that depend on React state for layout.
      */}
      {children}
    </AppContext.Provider>
  )
}

export const useApp = () => {
  const ctx = useContext(AppContext)
  if (!ctx) throw new Error('useApp must be inside AppProvider')
  return ctx
}
